require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HousingMobile' do
  config = use_native_modules!
  use_unimodules!(modules_paths: ['../node_modules'])
  use_react_native!(:path => config["reactNativePath"])

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
	# use_flipper!
	# post_install do |installer|
	#   flipper_post_install(installer)
  # end
end
